blog/urls.py
from django.urls import path

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))))

from blog import views

app_name = 'blog'

urlpatterns = [
    path('login/', views.login_func, name='login'),
    path('logout/', views.logout_func, name='logout'),
    path('liked/<int:pk>/', views.liked_func, name='liked'),
    path('status_open/<int:pk>/', views.status_open, name='status_open'),
    path('status_hidden/<int:pk>/', views.status_hidden, name='status_hidden'),
    path('comment/<int:post_pk>/', views.PostCommentView.as_view(), name='comment'),
    path('', views.CoverView.as_view(), name='cover'),
]

post_org_urlpatterns = [
    path('blog/', views.PostIndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('category/<int:pk>/', views.PostCategoryView.as_view(), name='category'),
]

post_mark_urlpatterns = [
    path('blog_mark/', views.PostIndexMarkView.as_view(), name='index_mark'),
    path('detail_mark/<int:pk>/', views.PostDetailMarkView.as_view(), name='detail_mark'),
    path('update_mark/<int:pk>/', views.PostUpdateMarkView.as_view(), name='update_mark'),
    path('create_mark/', views.PostCreateMarkView.as_view(), name='create_mark'),
    path('delete_mark/<int:pk>/', views.PostDeleteMarkView.as_view(), name='delete_mark'),
    path('category_mark/<int:pk>/', views.PostCategoryMarkView.as_view(), name='category_mark'),
]

todo_urlpatterns = [
    path('todo_list/', views.TodoList.as_view(), name='todo_list'),
    path('todo_detail/<int:pk>', views.TodoDetail.as_view(), name='todo_detail'),
    path('todo_create/', views.TodoCreate.as_view(), name='todo_create'),
    path('todo_delete/<int:pk>', views.TodoDelete.as_view(), name='todo_delete'),
    path('todo_update/<int:pk>', views.TodoUpdate.as_view(), name='todo_update'),
]

diary_urlpatterns = [
    path('diary_list/', views.IndexView.as_view(), name='diary_index'),
    path('diary_detail/<int:pk>', views.DetailView.as_view(), name='diary_detail'),
    path('diary_create/', views.CreateView.as_view(), name='diary_create'),
    path('diary_delete/<int:pk>', views.DeleteView.as_view(), name='diary_delete'),
    path('diary_update/<int:pk>', views.UpdateView.as_view(), name='diary_update'),
]

homepage_update_urlpatterns = [
    path('home/', views.HomeIndexView.as_view(), name='home'),
]

account_urlpatterns = [
    path('about/', views.ProfileIndexView.as_view(), name='about'),
]

urlpatterns += post_org_urlpatterns
urlpatterns += post_mark_urlpatterns
urlpatterns += todo_urlpatterns
urlpatterns += diary_urlpatterns
urlpatterns += homepage_update_urlpatterns
urlpatterns += account_urlpatterns

templates/pages/diary_create.html
{% extends 'base_diary.html' %}

{% block main_content %}
<div class="container">
  <form action="" method="POST">{% csrf_token %}
    <div class="form-group">
      <label for="exampleFormControlTextarea1">日付</label><br>
      {{ form.diary_date }}
    </div>
    <div class="form-group">
      <label for="exampleFormControlInput1">タイトル</label><br>
      <input type="text" class="form-control" id="exampleFormControlInput1" name='title' placeholder='入力必須です'>
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">日記</label><br>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="10" name='jp_text' placeholder="入力必須です"></textarea>
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">日記（英語）</label><br>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="10" name='en_text' placeholder="入力必須です"></textarea>
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">作成日</label><br>
        {{ form.created_at }}
    </div>
    <input type="submit" value="作成する" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">
    <a href="{% url 'blog:diary_index' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">戻る</a>
  </form>
</div>
{% endblock main_content %}

templates/pages/diary_delete.html
{% extends 'base_diary.html' %}

{% block main_content %}
<div class="container">
    <p>削除してもよろしいですか？　</p>
    <form action='' method="POST">{% csrf_token %}
        <input type="submit" value="削除します" class="alert alert-danger" role="alert">
    </form>
    <br>
    <a href="{% url 'blog:diary_index' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">戻る</a>
</div>
{% endblock main_content %}

templates/pages/diary_list.html
{% extends 'base_diary.html' %}


{% block main_content %}
<div class="container btn-toolbar">
  <div class="btn-group">
    <form>
      <a href="{% url 'blog:diary_create' %}" class="btn btn-success">新規作成</a>
    </form>
  </div>
  <div class="btn-group ml-auto">
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'blog:diary_index' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="keyword">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</div>
<div class="container">
  <br>
  <table class="table table-sm ">
    <thead class="thead-white">
      <tr>
        <th scope="col" style="width: 20%">#button</th>
        {% comment %} <th scope="col" style="width: 10%">regist</th> {% endcomment %}
        <th scope="col" style="width: 20%">date</th>
        <th scope="col" style="width: 60%">title</th>
      </tr>
    </thead>
    <tbody>
      {% for item in object_list %}
      <tr>
        <th scope="row"><a href="{% url 'blog:diary_detail' item.pk %}" class="btn btn-dark">詳細</a></th>
        <td>{{ item.diary_date |date:"Y/m/d"}}</td>
        <td>{{ item.title| truncatechars:30 }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include 'pages/page.html' %}
</div>

{% endblock main_content %}

templates/pages/main_home.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
{% endblock customcss %}


{% block header %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="first-slide opacity-50" src="{% static 'images/header_image1.jpg' %}" alt="First slide">
        <div class="container">
          <div class="carousel-caption text-left">
            <h1>Growing</h1>
            <p>
                "You want to know the difference between a master and a beginner ?<br>
                The master has failed more times than the beginner has ever tried."<br>
                 - Master Yoda.
            </p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'blog:index_mark'%}" role="button">Go to KnowHow</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="second-slide" src="{% static 'images/header_image2.jpg' %}" alt="Second slide">
        <div class="container">
          <div class="carousel-caption text-info">
            <h1>Improve</h1>
            <p>
                “If you can’t fly, then run, if you can’t run, then walk, if you can’t walk, then crawl, <br>
                but whatever you do, you have to keep moving forward.”
                 - Martin Luther King Jr.
            </p>
            <p><a class="btn btn-lg btn-info" href="https://qiita.com/believeriver/items/2204394cead531f6881c" role="button" target="_blank">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="third-slide opacity-50" src="{% static 'images/header_image3.jpg' %}" alt="Third slide">
        <div class="container">
          <div class="carousel-caption text-left text-warning">
            <h1>Stock Market</h1>
            <p>
                Markets can remain irrational longer than you can remain solvent.<br>
                Nobody rings a bell at the market bottom.<br>
                Past performance does not guarantee future results.<br>
            </p>
            <p><a class="btn btn-lg btn-warning" href="http://nonoco.believeriver.site:8501/" role="button" target="_blank">Japanese Stocks</a></p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>
{% endblock header %}

{% block main_content %}
<div class="container">
    <h3>更新履歴</h3>
    <table class="table table-sm ">
        <tbody>
            {% for item in object_list %}
            <tr>
                {% if forloop.counter == 1 %}
                    <th scope="row"><span class="badge badge-danger">New</span></th>
                {% else %}
                    <th scope="row"></th>
                {% endif %}
                <td>{{ item.updated_at|date:"Y/m/j" }}</td>
                <td>{{ item.title }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>

    <!-- Marketing messaging and featurettes
      ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <!-- Three columns of text below the carousel -->
    <div class="marketing">
        <div class="row">
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/home-img1.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>KnowHow</h2>
            <p>技術ノウハウのメモ一覧</p>
            <p><a class="btn btn-secondary" href="{% url 'blog:index_mark'%}" role="button">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/home-img2.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>My Qiita</h2>
            <p>私のQiita投稿</p>
            <p><a class="btn btn-secondary" href="https://qiita.com/believeriver/items/2204394cead531f6881c" role="button" target="_blank">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/home-img3.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>Reading</h2>
            <p>読書</p>
            <p><a class="btn btn-secondary" href="https://beginblog-yukisan.com/" role="button" target="_blank">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/header_image3.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>IR</h2>
            <p>日本高配当株情報(streamlit)</p>
            <p><a class="btn btn-secondary" href="http://streamlit.believeriver.site:8501/" role="button" target="_blank">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/header_image3.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>IR</h2>
            <p>日本高配当株情報(flask)</p>
            <p><a class="btn btn-secondary" href="https://irbank.believeriver.site/" role="button" target="_blank">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->


        {% if user.is_superuser %}
        <h3></h3>
        <div class="row bg-light py-5">
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/home-img2.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>To Do</h2>
            <span class="badge badge-danger">管理者用</span>
            <p>私のやることリスト</p>
            <p><a class="btn btn-secondary" href="{% url 'blog:todo_list' %}" role="button">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/home-img3.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>My Diary</h2>
            <span class="badge badge-danger">管理者用</span>
            <p>日記</p>
            <p><a class="btn btn-secondary" href="{% url 'blog:diary_index' %}" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/header_image3.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>IR</h2>
            <span class="badge badge-danger">管理者用</span>
            <p>日本高配当株情報(streamlit sharing)</p>
            <p><a class="btn btn-secondary" href="https://jpstockirapp-fwybv8zvbupbzosmpumdrb.streamlit.app/" role="button" target="_blank">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/home-img3.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>Git Hub</h2>
            <span class="badge badge-danger">管理者用</span>
            <p>Git Hub</p>
            <p><a class="btn btn-secondary" href="https://github.com/believeriver" role="button" target="_blank">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/home-img3.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>Conoha 管理画面</h2>
            <span class="badge badge-danger">管理者用</span>
            <p>Web公開サーバ</p>
            <p><a class="btn btn-secondary" href="https://manage.conoha.jp/Wing/Server" role="button" target="_blank">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/home-img3.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>Stripe 管理画面</h2>
            <span class="badge badge-danger">管理者用</span>
            <p>決済システム管理画面</p>
            <p><a class="btn btn-secondary" href="https://dashboard.stripe.com/test/apikeys" role="button" target="_blank">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/home-img3.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>RISSA</h2>
            <span class="badge badge-danger">管理者用</span>
            <p>情報処理安全確保支援士マイページ</p>
            <p><a class="btn btn-secondary" href="https://riss.ipa.go.jp/riss/portal" role="button" target="_blank">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/home-img3.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>IPA試験</h2>
            <span class="badge badge-danger">管理者用</span>
            <p>情報技術者試験マイページ</p>
            <p><a class="btn btn-secondary" href="https://itee.ipa.go.jp/ipa/user/public/?token=a3a857daca4f7dccf72bd7e74c7e2294899c49cbd4ee962ebb4042581f544e02" role="button" target="_blank">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'images/home-img3.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>ChatGPT3.5</h2>
            <span class="badge badge-danger">管理者用</span>
            <p>ウインストン</p>
            <p><a class="btn btn-secondary" href="https://chat.openai.com/c/c4625043-0906-4ddd-a3da-ca025d75ef63" role="button" target="_blank">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
        {% endif %}
    </div>

    <!-- START THE FEATURETTES -->
    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">KnowHow<span class="text-muted">Tips</span></h2>
        <p class="lead">
            プログラミング(特にPython関係),Linux,サーバ構築、ネットワークなど,
            私が興味を持って勉強している内容で技術的なメモを纏めています。
        </p>
      </div>
      <div class="col-md-5">
        <img class="featurette-image img-fluid " data-src="holder.js/500x500/auto" src="{% static 'images/home-img1.jpg' %}" alt="Generic placeholder image" style="width: 500px; height: 300px">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Quita <span class="text-muted">SLURM</span></h2>
        <p class="lead">
            Quitaにもいくつか技術メモをまとめています。
            SLURMという並列計算機のジョブスケジューラ環境構築についてまとめました。
        </p>
      </div>
      <div class="col-md-5 order-md-1">
        <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" src="{% static 'images/home-img2.jpg' %}" alt="Generic placeholder image" style="width: 500px; height: 300px">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">Hobby <span class="text-muted">Reading</span></h2>
        <p class="lead">
            私の趣味は読書です。私の読んだ本について感想などをまとめています。
        </p>
      </div>
      <div class="col-md-5">
        <img class="featurette-image img-fluid mx-auto" src="{% static 'images/home-img3.jpg' %}" alt="Generic placeholder image" style="width: 500px; height: 300px">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">IR <span class="text-muted">日本高配当株</span></h2>
        <p class="lead">
            日本高配当株のランキングと各企業の株価推移、およびIRBank情報から投資判断に必要と思われる８つの項目をピックアップします。
            これらの情報をpythonのstreamlitで見える化しました。
        </p>
      </div>
      <div class="col-md-5 order-md-1">
        <img class="featurette-image img-fluid " data-src="holder.js/500x500/auto" src="{% static 'images/header_image3.jpg' %}" alt="Generic placeholder image" style="width: 500px; height: 300px">
      </div>
    </div>

    <hr class="featurette-divider">
　　<!-- /END THE FEATURETTES -->
</div>

{% endblock main_content %}

templates/pages/post_mark_list.html
{% extends 'base_blog_mark.html' %}

{% block content %}
  {% if user.is_superuser %}
  <a href="{% url 'blog:create_mark' %}" class="btn btn-success">新規作成</a>
  <br><br>
  {% endif %}
  <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'blog:index_mark' %}">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="keyword">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
  <br>
  {% for post in post_list %}
    {% if post.status == 2 %}
      <div class="card">
        <div class="card-header bg-dark text-white">
          {{ post.created_at|date:"Y/m/d"}} : <span class="badge bg-secondary text-light">{{ post.category }}</span>
        </div>
        <div class="card-body">
          <h5 class="card-title">{{post.title}}</h5>
          <p class="card-text">{{ post.content| truncatechars:30 }}</p>
          <a href="{% url 'blog:detail_mark' post.pk %}" class="btn btn-dark" class="btn btn-dark">詳細</a>
        </div>
      </div>
      <br>
    {% elif post.status == 1 and user.is_superuser %}
      <div class="card">
        <div class="card-header bg-dark text-white">
          {{ post.created_at|date:"Y/m/d"}} : <span class="badge bg-secondary text-light">{{ post.category }}</span>
          <span class="badge bg-danger text-light">非公開</span>
        </div>
        <div class="card-body">
          <h5 class="card-title">{{post.title}}</h5>
          <p class="card-text">{{ post.content| truncatechars:30 }}</p>
          <a href="{% url 'blog:detail_mark' post.pk %}" class="btn btn-dark" class="btn btn-dark">詳細</a>
        </div>
      </div>
      <br>
    {% endif %}
  {% endfor %}
  {% include 'pages/page.html' %}

{% endblock %}

templates/pages/post_mark_update.html
{% extends 'base_blog_mark.html' %}

{% block content %}
<div class="container">
    <form action="" method="POST">{% csrf_token %}
        <div class="form-group">
          <label for="exampleFormControlInput1">タイトル</label><br>
          <input type="text" class="form-control" id="exampleFormControlInput1" name='title' value='{{post.title}}'>
        </div>
        <div class="form-group">
          <label for="exampleFormControlTextarea1">本文</label><br>
          <textarea class="form-control" id="exampleFormControlTextarea1" rows="15" name='content'>{{post.content}}</textarea>
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">作成日</label><br>
            {{ form.created_at}}
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">作成日</label><br>
            {{ form.category }}
        </div>
        <input type="submit" value="更新する" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">
        <a href="{% url 'blog:index_mark' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">戻る</a>
    </form>
    </div>
{% endblock content %}

templates/pages/post_update.html
{% extends 'base_blog.html' %}

{% block content %}
<div class="container">
    <form action="" method="POST">{% csrf_token %}
        {% comment %} {{form.as_p}} {% endcomment %}
            <div class="form-group">
              <label for="exampleFormControlInput1">タイトル</label><br>
              <input type="text" class="form-control" id="exampleFormControlInput1" name='title' value='{{post.title}}'>
            </div>
            <div class="form-group">
              <label for="exampleFormControlTextarea1">本文</label><br>
              {% comment %} <textarea class="form-control" id="exampleFormControlTextarea1" rows="15" name='text' placeholder='{{post.text}}'></textarea> {% endcomment %}
              <textarea class="form-control" id="exampleFormControlTextarea1" rows="15" name='text'>{{post.text}}</textarea>
            </div>
            <div class="form-group">
              <label for="exampleFormControlTextarea1">サンプルコード</label><br>
              <textarea class="form-control" id="exampleFormControlTextarea1" rows="15" name='codememo' >{{ post.codememo }}</textarea>
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">作成日</label><br>
                {{ form.created_at}}
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">作成日</label><br>
                {{ form.category }}
            </div>
        <input type="submit" value="更新する" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">
        <a href="{% url 'blog:index' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">戻る</a>
    </form>
    </div>
{% endblock content %}

templates/pages/todo_detail.html
{% extends 'base_todo.html' %}

{% block main_content %}
  <div class='container'>
    <div class="alert alert-success" role="alert">
      <p>タイトル：{{ object.title }}</P>
      <p>{{ object.memo | linebreaksbr | urlize }}</P>
      <p>登録日：{{ object.created_at }}</P>
      <p>期日：{{ object.duedate }}</P>
    </div>
    <br>
    <a href="{% url 'blog:todo_update' object.pk %}" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">編集</a>
    <a href="{% url 'blog:todo_list' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">戻る</a>
    
    <a href="{% url 'blog:todo_delete' object.pk %}" class="btn btn-danger" tabindex="-1" role="button" aria-disabled="true">削除</a>
  </div>
{% endblock main_content %}

templates/pages/todo_list.html
{% extends 'base_todo.html' %}

{% block main_content %}
<div class="container btn-toolbar">
  <div class="btn-group">
    <form>
      <a href="{% url 'blog:todo_create' %}" class="btn btn-success">新規作成</a>
    </form>
  </div>
  <div class="btn-group ml-auto">
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'blog:todo_list' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="keyword">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</div>
<br>
<div class="container">
    {% comment %} <a href="{% url 'blog:todo_create' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">新規作成</a>
    <br><br> {% endcomment %}
  <table class="table table-sm">
    <thead class="thead-white">
      <tr>
        <th scope="col" style="width: 5%">#button</th>
        {% comment %} <th scope="col" style="width: 10%">regist</th> {% endcomment %}
        <th scope="col" style="width: 15%">due date</th>
        <th scope="col" style="width: 15%">status</th>
        <th scope="col" style="width: 65%">title</th>
      </tr>
    </thead>
    <tbody>
      {% for item in object_list %}
      {% if item.priority == 'secondary' %}
      <tr scope="row" class="alert alert-dark" role="alert">
      {% elif item.priority == 'danger'%}
      <tr scope="row" class="alert alert-{{ item.priority }}" role="alert">
      {% else %}
      <tr scope="row" class="alert" role="alert">
      {% endif %}
        <th>
          <a href="{% url 'blog:todo_detail' item.pk %}" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">詳細</a>
          {% comment %} <a href="{% url 'blog:todo_update' item.pk %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">編集</a>
          <a href="{% url 'blog:todo_delete' item.pk %}" class="btn btn-primary" tabindex="-1" role="button" aria-disabled="true">削除</a> {% endcomment %}
        </th>
        {% comment %} <td>{{ item.created_at|date:"Y/m/d"}}</td> {% endcomment %}
        <td>{{ item.duedate|date:"Y/m/d"}}</td>
        <td>
          {% if item.priority == 'secondary'%}
          Close
          {% elif item.priority == 'danger'%}
          High
          {% else %}
          Normal
          {%endif%}
        </td>
        <td>{{ item.title| truncatechars:25 }}</td>
      </tr>
      {% endfor%}
    </tbody>
  </table>
  {% include 'pages/page.html' %}
</div>
{% endblock main_content %}