blog/urls.py
from django.urls import path

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))))

from blog import views

app_name = 'blog'

urlpatterns = [
    path('login/', views.login_func, name='login'),
    path('logout/', views.logout_func, name='logout'),
    path('liked/<int:pk>/', views.liked_func, name='liked'),
    path('status_open/<int:pk>/', views.status_open, name='status_open'),
    path('status_hidden/<int:pk>/', views.status_hidden, name='status_hidden'),
    path('comment/<int:post_pk>/', views.PostCommentView.as_view(), name='comment'),
    path('', views.CoverView.as_view(), name='cover'),
]

post_org_urlpatterns = [
    path('blog/', views.PostIndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('category/<int:pk>/', views.PostCategoryView.as_view(), name='category'),
]

post_mark_urlpatterns = [
    path('blog_mark/', views.PostIndexMarkView.as_view(), name='index_mark'),
    path('detail_mark/<int:pk>/', views.PostDetailMarkView.as_view(), name='detail_mark'),
    path('update_mark/<int:pk>/', views.PostUpdateMarkView.as_view(), name='update_mark'),
    path('create_mark/', views.PostCreateMarkView.as_view(), name='create_mark'),
    path('delete_mark/<int:pk>/', views.PostDeleteMarkView.as_view(), name='delete_mark'),
    path('category_mark/<int:pk>/', views.PostCategoryMarkView.as_view(), name='category_mark'),
]

todo_urlpatterns = [
    path('todo_list/', views.TodoList.as_view(), name='todo_list'),
    path('todo_detail/<int:pk>', views.TodoDetail.as_view(), name='todo_detail'),
    path('todo_create/', views.TodoCreate.as_view(), name='todo_create'),
    path('todo_delete/<int:pk>', views.TodoDelete.as_view(), name='todo_delete'),
    path('todo_update/<int:pk>', views.TodoUpdate.as_view(), name='todo_update'),
]

diary_urlpatterns = [
    path('diary_list/', views.IndexView.as_view(), name='diary_index'),
    path('diary_detail/<int:pk>', views.DetailView.as_view(), name='diary_detail'),
    path('diary_create/', views.CreateView.as_view(), name='diary_create'),
    path('diary_delete/<int:pk>', views.DeleteView.as_view(), name='diary_delete'),
    path('diary_update/<int:pk>', views.UpdateView.as_view(), name='diary_update'),
]

homepage_update_urlpatterns = [
    path('home/', views.HomeIndexView.as_view(), name='home'),
]

account_urlpatterns = [
    path('about/', views.ProfileIndexView.as_view(), name='about'),
]

urlpatterns += post_org_urlpatterns
urlpatterns += post_mark_urlpatterns
urlpatterns += todo_urlpatterns
urlpatterns += diary_urlpatterns
urlpatterns += homepage_update_urlpatterns
urlpatterns += account_urlpatterns

templates/snippets/footer.html
<!--<div class="bg-dark text-white text-center py-1">-->
<!--    <p>believeriver@copyright</p>-->
<!--</div>-->

<div class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; believeriver. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</div>

templates/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="{% url 'blog:cover' %}">Portfolio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:home' %}">Home</a>
      </li>
      {% if user.is_superuser %}
      <li class="nav-item">
         <a class="nav-link" href="{% url 'blog:logout' %}">logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:login' %}">login</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:about' %}">About</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Information
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'blog:index_mark' %}">KnowHow</a>
          <a class="dropdown-item" href="https://qiita.com/believeriver/items/2204394cead531f6881c" target="_blank">my qiita</a>
          <a class="dropdown-item" href="https://beginblog-yukisan.com/" target="_blank">Reading</a>
          <a class="dropdown-item" href="http://nonoco.believeriver.site:8501/" target="_blank">IR info</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Contact</a>
          {% if user.is_superuser %}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item text-success" href="{% url 'admin:index' %}">Admin</a>
          <a class="dropdown-item text-success" href="{% url 'blog:index' %}">KnowHow_original</a>
          <a class="dropdown-item text-success" href="{% url 'blog:todo_list' %}">Todolist</a>
          <a class="dropdown-item text-success" href="{% url 'blog:diary_index' %}">My Diary</a>
          <a class="dropdown-item text-success" href="#">Document</a>
          {% endif %}
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'blog:index' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="keyword">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>