blog/urls.py
from django.urls import path

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))))

from blog import views

app_name = 'blog'

urlpatterns = [
    path('login/', views.login_func, name='login'),
    path('logout/', views.logout_func, name='logout'),
    path('liked/<int:pk>/', views.liked_func, name='liked'),
    path('status_open/<int:pk>/', views.status_open, name='status_open'),
    path('status_hidden/<int:pk>/', views.status_hidden, name='status_hidden'),
    path('comment/<int:post_pk>/', views.PostCommentView.as_view(), name='comment'),
    path('', views.CoverView.as_view(), name='cover'),
]

post_org_urlpatterns = [
    path('blog/', views.PostIndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('category/<int:pk>/', views.PostCategoryView.as_view(), name='category'),
]

post_mark_urlpatterns = [
    path('blog_mark/', views.PostIndexMarkView.as_view(), name='index_mark'),
    path('detail_mark/<int:pk>/', views.PostDetailMarkView.as_view(), name='detail_mark'),
    path('update_mark/<int:pk>/', views.PostUpdateMarkView.as_view(), name='update_mark'),
    path('create_mark/', views.PostCreateMarkView.as_view(), name='create_mark'),
    path('delete_mark/<int:pk>/', views.PostDeleteMarkView.as_view(), name='delete_mark'),
    path('category_mark/<int:pk>/', views.PostCategoryMarkView.as_view(), name='category_mark'),
]

todo_urlpatterns = [
    path('todo_list/', views.TodoList.as_view(), name='todo_list'),
    path('todo_detail/<int:pk>', views.TodoDetail.as_view(), name='todo_detail'),
    path('todo_create/', views.TodoCreate.as_view(), name='todo_create'),
    path('todo_delete/<int:pk>', views.TodoDelete.as_view(), name='todo_delete'),
    path('todo_update/<int:pk>', views.TodoUpdate.as_view(), name='todo_update'),
]

diary_urlpatterns = [
    path('diary_list/', views.IndexView.as_view(), name='diary_index'),
    path('diary_detail/<int:pk>', views.DetailView.as_view(), name='diary_detail'),
    path('diary_create/', views.CreateView.as_view(), name='diary_create'),
    path('diary_delete/<int:pk>', views.DeleteView.as_view(), name='diary_delete'),
    path('diary_update/<int:pk>', views.UpdateView.as_view(), name='diary_update'),
]

homepage_update_urlpatterns = [
    path('home/', views.HomeIndexView.as_view(), name='home'),
]

account_urlpatterns = [
    path('about/', views.ProfileIndexView.as_view(), name='about'),
]

urlpatterns += post_org_urlpatterns
urlpatterns += post_mark_urlpatterns
urlpatterns += todo_urlpatterns
urlpatterns += diary_urlpatterns
urlpatterns += homepage_update_urlpatterns
urlpatterns += account_urlpatterns

templates/base.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <title>My Portfolio</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!--  carousel.css  -->
    <link href="{% static 'css/card_style.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/carousel.css' %}" rel="stylesheet">

    {% block customcss %}
    {% endblock customcss %}
  </head>

  <body>
  <header>
    {% block navbar %}
    {% include 'snippets/navbar.html' %}
    {% endblock navbar %}

    {% block header %}
    {% endblock header %}
  </header>

  <main>
    {% block main_content %}
    {% endblock main_content%}
  </main>

  <footer>
    {% block footer %}
    {% include 'snippets/footer.html' %}
    {% endblock footer%}
  </footer>

  <!-- Optional JavaScript -->
  <script src="{% static 'bootstrap/assets/js/vendor/popper.min.js' %}"></script>
  <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
  <script src="{% static 'bootstrap/assets/js/vendor/holder.min.js' %}"></script>

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  </body>
</html>

templates/base_blog.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/dracula.min.css">
<link href="{% static 'css/code_style.css' %}" rel="stylesheet">
<style type="text/css">
.jumbotron { background:url({% static 'images/home-img2.jpg' %})
             center no-repeat;
             background-size: cover;
             }
</style>
{% endblock customcss %}

{% block header %}
<div class="jumbotron ">
  <h1 class="display-4 text-primary">KnowHow</h1>
  <p class="lead text-light">
    技術的なメモを中心にまとめます。<br>
    検索にて調べることができます。
  </p>
</div>
{% endblock header %}

{% block main_content %}
<div class="container">
    <div class="row">
      <div class="col-md-9">
        {% block content %}
        {% endblock content %}
      </div>
      <div class="col-md-3">
        <ul class="list-group">
          <li class="list-group-item bg-dark text-white">カテゴリ一覧</li>
          {% for category in categories %}
            <li class="list-group-item">
              <a href="{% url 'blog:category' category.pk %}" class="text-dark">{{ category.name }}({{ category.count }})</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js"></script>
  <script>
      // ハイライトを実行
      hljs.initHighlightingOnLoad();
  </script>

{% endblock main_content%}

templates/base_blog_mark.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
<!-- For Markdown -->
  <link rel="stylesheet" href="{% static 'css/monokai.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism.min.css" />
  <script defer src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-core.min.js"></script>
  <script defer src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/line-numbers/prism-line-numbers.min.js"></script>
  <script>
  MathJax = {
    tex: {
      inlineMath: [['$', '$'], ['\\(', '\\)']]
    }
  };
  </script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.js"></script>
  <!--  <script id="MathJax-script" async src="{% static 'scripts/tex-mml-chtml.js' %}"></script>-->

  <style type="text/css">
  .jumbotron { background:url({% static 'images/home-img2.jpg' %})
               center no-repeat;
               background-size: cover;
               }
  </style>
{% endblock customcss %}

{% block header %}
  <div class="jumbotron ">
    <h1 class="display-4 text-primary">KnowHow</h1>
    <p class="lead text-light">
      技術的なメモを中心にまとめます。<br>
      検索にて調べることができます。
    </p>
  </div>
{% endblock header %}

{% block main_content %}
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        {% block content %}
        {% endblock content %}
      </div>
      <div class="col-md-3">
        <ul class="list-group">
          <li class="list-group-item bg-dark text-white">カテゴリ一覧</li>
          {% for category in categories %}
            <li class="list-group-item">
              <a href="{% url 'blog:category_mark' category.pk %}" class="text-dark">{{ category.name }}({{ category.count }})</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock main_content%}

templates/base_diary.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
<style type="text/css"><!--
/*ここに調整CSS記述*/-->
.jumbotron { background:url({% static 'images/home-img3.jpg' %})
             center no-repeat;
             background-size: cover;
             }
</style>
{% endblock customcss %}

{% block header %}
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">My Diary</h1>
      <p class="lead">私の日記帳です。英語日記も書きたいと思います。</p>
    </div>
  </div>
{% endblock header %}

templates/base_todo.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
<style type="text/css"><!--
/*ここに調整CSS記述*/-->
.jumbotron { background:url({% static 'images/home-img3.jpg' %})
             center no-repeat;
             background-size: cover;
             }
</style>
{% endblock customcss %}

{% block header %}
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Todolist</h1>
      <p class="lead">Todolistを作って毎日を効率的に過ごしましょう</p>
    </div>
  </div>
{% endblock header %}